# arclet — Azure Arc agent in a container, kind-style: real systemd as PID 1.
#
# Why systemd? The Connected Machine agent is designed to run as a set of
# systemd-managed services (himdsd, gcad, extd). With real systemd-as-PID-1
# we let systemctl do its normal job — graceful service lifecycle, dependency
# ordering, on-failure restarts — and the in-memory cloud-endpoints state
# survives the post-connect daemon restarts that azcmagent triggers.
#
# Build:  docker build -t arclet:dev .
# Run:    see README.md (requires --tmpfs /tmp /run /run/lock + --privileged,
#         or equivalent caps, plus cgroup mounts on older Dockers).

FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

# Base tooling + systemd (with systemd-sysv to get /sbin/init).
# dbus is required by systemctl's d-bus IPC at runtime.
# apt-get upgrade picks up Ubuntu CVE fixes for transitively-installed
# packages (glibc, openssl, etc.) that aren't refreshed by a plain
# `apt-get install <named-pkgs>` against the current base layer.
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends \
        systemd systemd-sysv dbus \
        openssh-server \
        ca-certificates curl gnupg lsb-release jq sudo \
        iproute2 procps \
 && rm -rf /var/lib/apt/lists/*

# Install azcmagent. Two build-time problems to solve:
#   1. /opt/GC_Service/GC/install.sh reads /proc/1/comm and bails unless it
#      contains "systemd" or "init". At build time PID 1 is bash. We work
#      around by exec'ing through a copy of bash *named* systemd, placed in
#      a separate directory so it CANNOT clobber the real /usr/bin/systemd
#      symlink that points to /lib/systemd/systemd.
#   2. azcmagent's postinst calls `systemctl start himdsd.service` (and
#      friends). With no systemd running as PID 1 yet, that fails. We
#      dpkg-divert the real systemctl out of the way during install and
#      drop in a no-op shim. After install we put the real systemctl back
#      and manually `systemctl enable` the units we want.
#
# The compound `;` joins (with set -euo pipefail) prevent bash from
# exec-optimizing into the last command and silently losing PID 1.
COPY systemctl-install-shim /build-shims/systemctl-install-shim
RUN mkdir -p /build-shims \
 && cp /usr/bin/bash /build-shims/systemd \
 && chmod +x /build-shims/systemctl-install-shim \
 && exec /build-shims/systemd -c '\
        set -euo pipefail; \
        dpkg-divert --local --add --rename --divert /usr/bin/systemctl.real /usr/bin/systemctl; \
        install -m 0755 /build-shims/systemctl-install-shim /usr/bin/systemctl; \
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg; \
        echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/microsoft.list; \
        apt-get update; \
        apt-get install -y --no-install-recommends azcmagent; \
        rm -rf /var/lib/apt/lists/*; \
        rm /usr/bin/systemctl; \
        dpkg-divert --local --remove --rename /usr/bin/systemctl; \
        systemctl enable himdsd.service; \
        systemctl enable arcproxyd.service; \
        systemctl enable gcad.service; \
        systemctl enable extd.service; \
        rm -rf /build-shims; \
        :'

# Mask units that either don't make sense in a container or — critically —
# would reach into the host kernel's namespace-LESS state and clobber it.
#
# binfmt_misc is the canonical hazard: the kernel exposes a single global
# /proc/sys/fs/binfmt_misc that every container with CAP_SYS_ADMIN can
# write to. An unmasked in-container systemd-binfmt does:
#   1) write -1 to every existing entry (flushing the host's registrations,
#      including WSLInterop on WSL — which breaks host-side `az`, `gh.exe`,
#      `docker.exe`, anything that interops with Windows),
#   2) then re-register only what its own /usr/lib/binfmt.d/ ships
#      (e.g. python3.12 on Ubuntu 24.04).
# Masking systemd-binfmt.service AND the auto/mount units stops the
# container from ever touching that surface, regardless of --privileged.
#
# Keep this list otherwise small; add only as needed.
RUN systemctl mask \
        systemd-binfmt.service \
        proc-sys-fs-binfmt_misc.automount \
        proc-sys-fs-binfmt_misc.mount \
        sys-fs-fuse-connections.mount \
        sys-kernel-config.mount \
        systemd-modules-load.service \
        systemd-udevd.service \
        systemd-udevd-control.socket \
        systemd-udevd-kernel.socket \
        getty.target \
        systemd-tmpfiles-setup-dev.service

# SSH: hardened config + persisted host keys.
#
# Delete any host keys generated by the openssh-server postinst: they would
# be baked into the image and shared by every container pulled from it,
# which breaks SSH host-key TOFU and lets anyone with the public image
# impersonate any deployed container. entrypoint.sh runs `ssh-keygen -A`
# at first boot to mint a unique set; mount /etc/ssh as a volume to
# persist them across container recreates.
COPY sshd_config /etc/ssh/sshd_config
RUN rm -f /etc/ssh/ssh_host_*_key /etc/ssh/ssh_host_*_key.pub \
 && mkdir -p /run/sshd /etc/ssh \
 && systemctl enable ssh.service

# Arc onboarding: oneshot unit invoked on every boot. Idempotency lives in
# the script (see /usr/local/bin/arc-connect), NOT in ConditionPathExists,
# because a partial connect can leave agentconfig.json present but
# cloudconfig.json missing — exactly the failure mode we want to recover
# from on the next boot.
COPY arc-connect /usr/local/bin/arc-connect
COPY arc-connect.service /etc/systemd/system/arc-connect.service
RUN chmod +x /usr/local/bin/arc-connect \
 && systemctl enable arc-connect.service

# Entrypoint wrapper materializes runtime config (SSH authorized keys,
# /etc/arc-connect.env from ARC_* env vars or mounts) BEFORE exec'ing
# /sbin/init.
COPY entrypoint.sh /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

# Clear the image-baked machine-id. systemd generates a fresh one at
# first boot when /etc/machine-id is empty. Without this, every
# container from this image shares one systemd/D-Bus identity, which
# confuses journald and any consumer that keys off machine-id.
RUN : >/etc/machine-id \
 && rm -f /var/lib/dbus/machine-id

# No EXPOSE / -p needed: SSH reaches this container over the Arc
# HybridConnectivity tunnel (`az ssh arc` / `aztunnel arc connect`), not
# from the Docker host.

# systemd uses SIGRTMIN+3 for graceful shutdown.
STOPSIGNAL SIGRTMIN+3

ENTRYPOINT ["/usr/local/bin/entrypoint"]
CMD ["/sbin/init"]
